version: 2
jobs:
  build:
    working_directory: /temp
    docker:  
      - image: mono:latest
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
    steps:
      - checkout
      - run: msbuild Analytics/Analytics.csproj /t:restore
      - run: msbuild Analytics/Analytics.csproj /p:Configuration=Release
      - run: msbuild Analytics.Net35/Analytics.Net35.csproj /t:restore
      - run: msbuild Analytics.Net35/Analytics.Net35.csproj /p:Configuration=Release
      - run: nuget pack Analytics.nuspec
  test:
    working_directory: /test
    docker:  
      - image: microsoft/dotnet:1.1.1-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
    steps:
      - checkout
      - run: dotnet restore Test/Test.csproj
      - run: dotnet test Test/Test.csproj
  test_35:
    working_directory: /test35
    docker:  
      - image: mono:latest
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
    steps:
      - checkout
      - run: nuget restore
      - run: msbuild Test.Net35/Test.Net35.csproj /t:restore
      - run: msbuild Test.Net35/Test.Net35.csproj /p:Configuration=Release
      - run: mono --debug ./packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe Test.Net35/bin/Release/Test.Net35.dll
  code_coverage:
    working_directory: /code_coverage
    docker:
      - image: brian9206/dotnet-framework-msbuild
    steps:
      - checkout
      - run: nuget restore
      - run: msbuild Test.Net35/Test.Net35.csproj /t:restore
      - run: msbuild Test.Net35/Test.Net35.csproj /p:Configuration=Debug
      - run: nuget install opencover -version 4.6.519
      - run: ./OpenCover.4.6.519/tools/OpenCover.Console.exe -register:user "-filter:+[Bom]* -[*Test]*" "-target:./packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe" "-targetargs:/noshadow Test.Net35/bin/Debug/Test.Net35.dll"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - test_35
      - code_coverage