version: 2
jobs:
  build:
    working_directory: /temp
    docker:  
      - image: mono:latest
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
    steps:
      - checkout
      - run: nuget restore
      - run: msbuild Analytics/Analytics.csproj /t:restore
      - run: msbuild Analytics/Analytics.csproj /p:Configuration=Release
      - run: msbuild Analytics.Net35/Analytics.Net35.csproj /t:restore
      - run: msbuild Analytics.Net35/Analytics.Net35.csproj /p:Configuration=Release
      - run: nuget pack Analytics.nuspec
  test:
    working_directory: /test
    docker:  
      - image: microsoft/dotnet:1.1.1-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OUTPUT: 1
    steps:
      - checkout
      - run: dotnet restore Test/Test.csproj
      - run: dotnet build Test/Test.csproj
      - run: nuget install Newtonsoft.Json -Version 10.0.3
      - run: nuget install xunit.assert -Version 2.3.0-beta1-build3642
      - run: nuget install xunit.runner.console -Version 2.3.0-beta1-build3642
      - run: nuget install xunit.extensibility.execution -Version 2.3.0-beta1-build3642
      - run: mv Newtonsoft.Json/lib/netstandard1.0/*.* Test/bin/Debug/netcoreapp1.1/
      - run: mv xunit.assert.2.3.0-beta1-build3642/lib/netstandard1.1/*.* Test/bin/Debug/netcoreapp1.1/
      - run: mv xunit.runner.console.2.3.0-beta1-build3642/tools/*.* Test/bin/Debug/netcoreapp1.1/
      - run: mv xunit.extensibility.core.2.3.0-beta1-build3642/lib/netstandard1.1/*.* Test/bin/Debug/netcoreapp1.1/ -f
      - run: mv xunit.extensibility.execution.2.3.0-beta1-build3642/lib/netstandard1.1/*.* Test/bin/Debug/netcoreapp1.1/ -f
      - run: cd Test/bin/Debug/netcoreapp1.1/ && xunit.console.exe Test.dll -noshadow -nologo -xml Test_Coverage.xml
  test_code_coverage:
    working_directory: /test_code_coverage
    docker:
      - image: mono:latest
    steps:
      - checkout
      - run: nuget restore
      - run: msbuild Test.Net35/Test.Net35.csproj /t:restore
      - run: msbuild Test.Net35/Test.Net35.csproj /p:Configuration=Debug
      - run: mono --debug --profile=monocov ./packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe Test.Net35/bin/Debug/Test.Net35.dll
      - run: curl -s https://codecov.io/bash > codecov
      - run: chmod +x codecov
      - run: ./codecov -f "TestResult.xml"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - test_code_coverage